import re

RE_PUNCT = re.compile(r'\W+')

COMPANY_KEY_CODES = {
    re.compile(k): v for k, v in {
        'ag': '',
        'advisor': 'ad',
        'advisors': 'ad',
        'advisory': 'ad',
        'american?': 'us',
        'assets?': 'at',
        'asset mn': 'am',
        'associates?': 'as',
        'bv': '',
        'bank(ing|s)?': 'bk',
        'broker(s|age)': 'br',
        'business(es)?': 'bs',
        'canada': 'ca',
        'capital': 'cp',
        'capital mn': 'cm',
        'centers?': '',
        'co': '',
        'colleges?': 'cg',
        'compan(y|ies)': '',
        'consulting': 'cn',
        'corp': '',
        'corporat(e|ion)': '',
        'developments?': 'dv',
        'energy': 'en',
        'enterprises?': 'et',
        'executives?': 'ex',
        'financ(e|ial|ing)': 'fn',
        'fund(s|ing)': 'fd',
        'gmbh': '',
        'group': '',
        'healthcar(es?|ing)': 'hc',
        'holdings?': '',
        'inc': '',
        'incorporated': '',
        "intl": 'it',
        'internationals?': 'it',
        'investments?': 'iv',
        'investment advisor(s|y)?': 'ia',
        'investment mn': 'im',
        'lc': '',
        'llc': '',
        'llp': '',
        'lc': '',
        'lp': '',
        'limited': '',
        'ltd': '',
        'management': 'mn',
        'medicals?': 'md',
        'medicines?': 'md',
        'na': '',
        'nv': '',
        'na': '',
        'network(s|ings?)?': 'nw',
        'networkings?': 'nw',
        'ptv': 'pv',
        'partner(s|ship)?': 'pt',
        'private': 'pv',
        'product(s|ions?)?': 'pd',
        'ptv': 'pv',
        'resources?': 'rs',
        'sa': '',
        'sas': '',
        'spa': '',
        'securities': 'sc',
        'service': 'sv',
        'services?': 'sv',
        'solutions?': 'sl',
        'strateg(ies|y)': 'sr',
        'systems?': 'sy',  # XXX
        'tech': 'tc',
        'technologies': 'tc',
        'technology': 'tc',
        'the': '',
        'trade': 'td',
        'trader': 'td',
        'traders': 'td',
        'trades': 'td',
        'trading': 'td',
        'tradings': 'td',
        'us': 'us',
        'universities': 'un',
        'university': 'un',
        'venture': 'vt',
        'ventures': 'vt',
        'as': '',
        'and': '',
        'of': '',
        'plc': '',
        'ptv': 'pv',
        'sec': 'sc'
    }.items()
}
